server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: patient-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/patient_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
