server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

security:
  jwt:
    private-key-path: classpath:keys/private.pem
    public-key-path: classpath:keys/public.pem

springdoc:
  swagger-ui:
    path: /swagger-ui.html